from selenium.webdriver.common.by import By

ORDER_FEED = (By.XPATH, './/p[text()="Лента Заказов"]')
ORDER_1 = (By.XPATH, './/h2[@class="text text_type_main-medium mb-2"][1]')
MODAL_WINDOW = (By.XPATH, '//*[@id="root"]/div/section[2]/div[1]/div')
#details = (By.XPATH, '//p[text()="Cостав"]')
#title = (By.XPATH, '//h1[text()="Лента заказов"]')
LOGIN_BUTTON_ON_MAIN = (By.XPATH, './/*[@id="root"]/div/main/section[2]/div/button')
total_order_count = (By.XPATH, "//p[text()='Выполнено за все время:']/following-sibling::p")
daily_order_count = (By.XPATH, "//p[text()='Выполнено за сегодня:']/following-sibling::p")
in_progress_order_count = (By.XPATH, ".//li[contains(@class, 'text_type_digits-default')]")
order_window = (By.XPATH, ".//li[contains(@class, 'OrderHistory_listItem__2x95r')][1]")
order_history = (By.XPATH, './/p[contains(@class, "text_type_digits-default")]')
#order_id = (By.XPATH, './/p[@class="text text_type_digits-default"]')
order_history_item_id = (By.XPATH, './/p[@class="text text_type_digits-default"]')
order_id = (By.XPATH, '//*[@id="root"]/div/section/div[1]/div/h2')
